replicaCount: 2

extraIngresses:
  - nameSuffix: flags
    className: kong
    annotations:
      kubernetes.io/ingress.class: kong
      cert-manager.io/cluster-issuer: letsencrypt-http
      konghq.com/strip-path: "false"
      konghq.com/methods: GET,OPTIONS
      konghq.com/plugins: platform-cors-prd
    hosts:
      - host: api.mereb.app
        paths:
          - path: /flags
            pathType: Prefix
            servicePort: http
    tls:
      - secretName: ops-prd-tls
        hosts:
          - api.mereb.app
  - nameSuffix: invite-redeem
    className: kong
    annotations:
      kubernetes.io/ingress.class: kong
      cert-manager.io/cluster-issuer: letsencrypt-http
      konghq.com/strip-path: "false"
      konghq.com/methods: POST,OPTIONS
      konghq.com/plugins: platform-cors-prd
    hosts:
      - host: api.mereb.app
        paths:
          - path: /invite/redeem
            pathType: Prefix
            servicePort: http
    tls:
      - secretName: ops-prd-tls
        hosts:
          - api.mereb.app

configMap:
  data:
    PORT: "4009"
    OIDC_AUDIENCE: account
    OPS_DEFAULT_FLAGS: >-
      [{"key":"inviteOnlyRegistration","description":"Require invite redemption through /register for pilot signups.","enabled":false}]
    PROFILE_BOOTSTRAP_URL: http://svc-profile.apps-prd.svc.cluster.local/internal/users/bootstrap
    REDIS_URL: redis://platform-prd-redis.platform-prd.svc.cluster.local:6379
    KAFKA_BROKERS: redpanda-platform-prd:9092
    SPLUNK_HEC_URL: https://splunk-hec.mereb.app/services/collector/event
    SPLUNK_HEC_INDEX: logs-prd

resources:
  requests:
    cpu: 50m
    memory: 256Mi

autoscaling:
  enabled: false
