replicaCount: 1

extraIngresses:
  - nameSuffix: flags
    className: kong
    annotations:
      kubernetes.io/ingress.class: kong
      cert-manager.io/cluster-issuer: letsencrypt-http
      konghq.com/strip-path: "false"
      konghq.com/methods: GET,OPTIONS
      konghq.com/plugins: platform-cors-stg
    hosts:
      - host: api-stg.mereb.app
        paths:
          - path: /flags
            pathType: Prefix
            servicePort: http
    tls:
      - secretName: ops-stg-tls
        hosts:
          - api-stg.mereb.app
  - nameSuffix: invite-redeem
    className: kong
    annotations:
      kubernetes.io/ingress.class: kong
      cert-manager.io/cluster-issuer: letsencrypt-http
      konghq.com/strip-path: "false"
      konghq.com/methods: POST,OPTIONS
      konghq.com/plugins: platform-cors-stg
    hosts:
      - host: api-stg.mereb.app
        paths:
          - path: /invite/redeem
            pathType: Prefix
            servicePort: http
    tls:
      - secretName: ops-stg-tls
        hosts:
          - api-stg.mereb.app

configMap:
  data:
    PORT: "4009"
    OIDC_AUDIENCE: account
    PROFILE_BOOTSTRAP_URL: http://svc-profile-stg.apps-stg.svc.cluster.local/internal/users/bootstrap
    REDIS_URL: redis://platform-stg-redis.platform-stg.svc.cluster.local:6379
    KAFKA_BROKERS: redpanda-platform-stg:9092
    SPLUNK_HEC_URL: https://splunk-hec.mereb.app/services/collector/event
    SPLUNK_HEC_INDEX: logs-stg

resources:
  requests:
    cpu: 25m
    memory: 128Mi

autoscaling:
  enabled: false
