nameOverride: svc-ops

replicaCount: 1

imagePullSecrets:
  - regcred

image:
  repository: registry.leultewolde.com/mereb/svc-ops
  env:
    - name: NODE_ENV
      value: production
    - name: SERVICE_NAME
      value: svc-ops
  envFrom:
    - configMapRef:
        name: svc-ops-dev-config
    - secretRef:
        name: svc-ops-dev-secrets
        optional: true

service:
  ports:
    - name: http
      port: 80
      targetPort: http
      containerPort: 4009

ingress:
  enabled: true
  className: kong
  annotations:
    kubernetes.io/ingress.class: kong
    cert-manager.io/cluster-issuer: letsencrypt-http
    konghq.com/strip-path: "true"
  hosts:
    - host: api-dev.mereb.app
      paths:
        - path: /ops
          pathType: Prefix
          servicePort: http
  tls:
    - secretName: ops-dev-tls
      hosts:
        - api-dev.mereb.app

configMap:
  enabled: true
  nameOverride: svc-ops-dev-config
  data:
    PORT: "4009"
    OIDC_ISSUER: https://auth.mereb.app/realms/mereb
    OIDC_AUDIENCE: account
    REDIS_URL: redis://platform-dev-redis.platform-dev.svc.cluster.local:6379
    KAFKA_BROKERS: redpanda-platform-dev:9092

resources:
  requests:
    cpu: 50m
    memory: 128Mi

autoscaling:
  enabled: false
